# Generated by Django 5.2.2 on 2025-06-05 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reponse_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='feed.message'),
        ),
    ]
